Add missing type definitions for initialize method
mozilla/source-map pull request #405
Opened 2019-09-02 11:53 UTC by NickolasBoyer

2021-02-17 14:34 UTC, danvoyce commented
Any chance of getting this merged one day?

2022-10-17 10:07 UTC, ochameau requested changes
Thanks for your patch.

Sorry for getting back to you so late, but main contributors to this package went away from this project.

I'd be happy to merge this pull request if you rebase and address the arraybuffer issue.

2022-10-17 10:07 UTC, ochameau commented on source-map.d.ts
> +    "lib/mappings.wasm": string;
This can also be an ArrayBuffer:
https://github.com/mozilla/source-map/blob/7a263408de1b60e60b6220ca3e36d9b3e4aa047d/lib/read-wasm-browser.js#L6-L11

2023-08-24 11:55 UTC, rmuratov commented
Looks like this already in the master (but not published to npm yet).

2023-08-24 12:43 UTC, willwillems commented
@rmuratov thanks! In that case I'm closing this one, tbh I don't even remember creating it 😅

2023-08-24 12:43 UTC, closed without merging